### ISSUE TITLE
Container with volume-from not working with nfs-client container.

### ISSUE THREAD

**Issue by ephillipe** [cpuguy83/docker-nfs-client#3]
I follow this [link](http://container42.com/2014/03/29/docker-quicktip-4-remote-volumes/) instructions to make one container import volumes from nfs-client container.

When I list files from **nfs-client** container I can get nfs files. I i list files from **app** container the folder is empty. 

What I missing?

Above my docker-compose used in Rancher environment to test NFS.

```
app:
  external_links:
  - moodle/ead-nfs:nfs
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: ubuntu
  working_dir: /moodledata
  volumes_from:
  - nfs-client
  stdin_open: true
nfs-client:
  environment:
    PARAMS: sync,ac,proto=tcp,port=2049
  external_links:
  - moodle/ead-nfs:nfs
  labels:
    io.rancher.sidekicks: app
    io.rancher.container.pull_image: always
  tty: true
  command:
  - /moodledata:/moodledata
  image: ephillipe/docker-nfs-client
  privileged: true
  volumes:
  - /moodledata
  working_dir: /moodledata
  stdin_open: true
```

Here some more tests:

```
ubuntu@ip-172-31-86-1:~$ docker run --rm --volumes-from e5ead3d3a2f8 ubuntu ls -lh /moodledata
total 0
ubuntu@ip-172-31-86-1:~$ docker exec e5ead3d3a2f8 bash -c "ls -lh /moodledata"
total 24K
drwxrwxrwx   3 root root 4.0K Jul 12 20:31 admin_report_customsql
drwxrwxrwx 246 root root 4.0K Jul 12 20:31 filedir
drwxrwxrwx   4 root root 4.0K Jul 12 20:31 lang
drwxrwxrwx   3 root root 4.0K Jul 12 20:31 mdeploy
drwxrwxrwx   2 root root 4.0K Jul 12 20:31 muc
drwxrwxrwx  40 root root 4.0K Jul 12 20:31 trashdir
ubuntu@ip-172-31-86-1:~$
```
